name: Run Stock Scanner

on:
  schedule:
    # Example: '30 9 * * 1-5' is 9:30 AM IND, Mon-Fri
    - cron: '0 4 * * 1-5'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install yfinance pandas requests smartapi-python pyotp logzero websocket-client

      - name: Run Python script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{secrets.CHAT_ID}}
          ADMINID: ${{secrets.ADMINID}}
          API_KEY: "Y8r5TcWG"
          TOTP_SECRET: "NPWR5ZRP33TM64JQOM6B54VRJM"
          CLIENT_CODE: "AABM100190"
          PASSWORD: "3641"
        run: python Volumescanner.py
